### ISSUE TITLE
Woobo Key chain

### ISSUE THREAD

**Issue by guoshen414** [Woobo/Design_Hardware#10]
Mirror issue here
https://trello.com/c/PUe6DPVv/195-woobo-plastic-keychain

Make a keychain version of a small woobo character. it can be rubber, silicone or plush.

Provide renderings of how it will look like.

Some initial drawings
![042c6b26-a213-4af9-9d22-812ae5cbed8a](https://user-images.githubusercontent.com/18539830/35119010-aa8032b0-fc61-11e7-92d5-9cf4706910b4.jpeg)

**Comment by issues-mover** [comment]
This issue was moved to Woobo/Design_UIUX#95
