### ISSUE TITLE
Woobo plus

### ISSUE THREAD

**Issue by guoshen414** [Woobo/Design_Hardware#11]
#We are going to make a large version of woobo at some point. We need a larger screen（and camera) so we can display more complex content and videos. However, we need to know following things

1. what are the competitors(mostly smart speaker with screen) out there? I know there are lots of new palyers coming out this CES. Make a simple competitor report focus mostly on appearance and ID design
2. Should it be a woobo character or more lean looking like a smart speaker with screen, or even tablet, Make sketches and renders for potential product Idea
3. Design the UI for the hardware. research to decide how many buttons and how to use it.

mirror issue
https://trello.com/c/m75GmUr0/194-woobo-50-plus

**Comment by issues-mover** [comment]
This issue was moved to Woobo/Design_UIUX#104
