### ISSUE TITLE
Propose a product idea

### ISSUE THREAD

**Issue by guoshen414** [Woobo/Design_Hardware#12]
An open project that you define yourself. I want you able to have a project for you own that go through the whole design process. You can do some research and brainstorm ideas for any children connected toy & device that will make a good addition to our product line. make sure you go through these steps.

1. Define the Problem
You can’t find a solution until you have a clear idea of what the problem is. Define what is the painpoint.

2. Collect Information
Collect sketches, take photographs and gather data to start giving you inspiration. if you want to do customer research talk to Katherine & Susana she has the connection to a good number of parents and children

3. Brainstorm and Analyze Ideas
Begin to sketch, make, and study so you can start to understand how all the data and information you’ve collected may impact your design.

4. Develop Solutions
Take your preliminary ideas and form multiple small-scale design solutions. (make quick concept models)

5. Gather Feedback
Present your ideas to as many people as possible: friends, teachers, professionals, and any others you trust to give insightful comments.

6. Improve
Reflect on all of your feedback and decide if or to what extent it should be incorporated. It is often helpful to take solutions back through the Design Process to refine and clarify them.

Make a small presentation that documents all these steps and provide a complete product solution with 

- [ ] CAD models
- [ ] UIUX design
- [ ] Manufacturing details.

**Comment by issues-mover** [comment]
This issue was moved to Woobo/Design_UIUX#97
