### ISSUE TITLE
realistic woobo plastic/sillicone 3d print

### ISSUE THREAD

**Issue by guoshen414** [Woobo/Design_Hardware#16]
after finishing adjust the sillicone/plastic version of woobo we need to think of the manufacture and testing with the customer. to help us decide the specific material and improve on the appearance. we need to have a realistic version we can show people. You can work with our printiner and use spray paint and print out the face for now. When we get closer to the final version, I can help you send those file to a better printer or even send to factory for a sample plastic mold

**Comment by issues-mover** [comment]
This issue was moved to Woobo/Design_UIUX#101
